---
- name: Install base development packages
  homebrew: 
    name: "{{item}}"
    update_homebrew: yes
    upgrade_all: yes
    state: latest
  with_items:
    - coreutils
    - imagemagick  
    - ack
    - jq
    - awscli
    - heroku-toolbelt
    - hh
    - cmake
    - docker
    - docker-machine

- name: Install base development applications
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - iterm2
    - sqlworkbenchj
    - dash
    - virtualbox

- name: Copy ack configuration file
  copy: >
    src=ackrc
    dest=~/.ackrc
    mode=644

- include: copy_ssh.yml
- include: sqlworkbenchj_config.yml
