---

- name: Install databases
  homebrew:
    name: "{{ item }}"
    update_homebrew: yes
    upgrade_all: yes
    state: latest
  with_items:
    - postgresql
    - redis
    - mongodb

- name: Start services at login
  file: src=/usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist path=~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist state=link force=yes
  with_items: 
    - postgresql
    - redis
    - mongodb

- name: Setup launch agents for services
  command: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
  with_items:
    - postgresql
    - redis
    - mongodb
    
- name: Copy psqlrc file to the root
  copy: >
    src=psqlrc
    dest=~/.psqlrc

- name: Create db zsh initializer folder
  file: path=~/.zsh/db state=directory

- name: Copy shell configs for databases
  copy:
    src={{item}}
    dest=~/.zsh/db/{{ item }}
  with_items:
    - aliases.zsh

- name: Init postgres
  command: initdb /usr/local/var/postgres creates=/usr/local/var/postgres/PG_VERSION
